### ISSUE TITLE
DAO Factory Mainnet launch

### ISSUE THREAD

**Issue by EvgenRad81** [airalab/DAO-factory#5]
Cоздаем DAO Factory в основной сети Ethereum.

Параметры DAO Factory:
Shares - 10000
Credits - не создаем
Market - не создаем

Все доходы от работы Builders идут на address - 0x2e3e8f5dac79E49e199E86f4226511261e3704dD

На начальном этапе нужны следующие Builders по указанным ценам:

BuilderDAO - 0.5 Eth
BuilderTokenEther - 0.2 Eth
BuilderTokenEmission - 0.2 Eth
BuilderMarket - 0.3 Eth
BuilderOffer - 0.1 Eth

**Comment by akru** [comment]
Добавил BuilderBoardOfDirectors - 0.8 Eth
