### ISSUE TITLE
DAO factory contract release list

### ISSUE THREAD

**Issue by ensrationis** [airalab/DAO-factory#6]
**release 0.1.0 "Registrar service":**
- Owned Registrar.sol

**release 0.2.0 "Token release":**
- ERC 20 token (Token.sol)
- TokenEmission.sol
- TokenEmissionACL.sol
- TokenEther.sol

**release 0.3.0 "BoD":**
- Voting51.sol
- BoardOfDirectors.sol updated with [DAO Airalab issue 2](https://github.com/airalab/DAO-Airalab/issues/2)

**Comment by akru** [comment]
### Libraries
| Contract name | Gas | Tx |
| :------------------|:-------|:-----|
| AddressList |  642952 | [ 0x60170788...](https://testnet.etherscan.io/tx/0x6017078873bf6437c84ca7d4efaa7ccc68a58f6f3463571560c992894c762e09)|
| AddressMap | 531175 | [0x93c0bb33...](https://testnet.etherscan.io/tx/0x93c0bb33ab132668b168a890f355177012b80acc207ceb42ded56b291d3847e0) |

**Comment by akru** [comment]
### Creators
| Contract name | Gas | Tx |
| :------------------|:-------|:-----|
| CreatorCore | 2076565 | [0xa08f4f9e...](https://testnet.etherscan.io/tx/0xa08f4f9e25acc4fad1ac0704ff50423508a1d4252b0ac09347b4b0b9482708b7) |
| CreatorOwnedRegistrar | 1358861 | [0x58c98a7d...](https://testnet.etherscan.io/tx/0x58c98a7de6ae8ed53a6e167c9dff1ec9a3644263196f120bf19bcddb8ac2088c) |
| CreatorToken | 1512786 | [0x8b76df9d...](https://testnet.etherscan.io/tx/0x8b76df9d343cb5f73478eb054c9f39173872804d48c42f88f4085d3e27cbfc71) |
| CreatorTokenEmission | 1635118 | [0xfaff3d09...](https://testnet.etherscan.io/tx/0xfaff3d0942b6cb9fbf7249573380a33a5a8d33081312033de422d874f5b7ae25) |
| CreatorTokenEmissionACL | 1960061 | [0x300d3d45...](https://testnet.etherscan.io/tx/0x300d3d45f6554a9ea874d78281732b06747551fa74bfc1d8641f9b733daba2cf) |
| CreatorTokenEther | 1616926 | [0x32ab2c81...](https://testnet.etherscan.io/tx/0x32ab2c8106b65680f730f924a82786e4a35a842e2d438fece20d3a76bc1ee076) |
| CreatorACLStorage | 1274999 | [0x1b2b7dd5...](https://testnet.etherscan.io/tx/0x1b2b7dd5fd7116e865f5d1d24bffad763bf44b90cce8690ab2ee0d6e34177ade) |
| CreatorVoting51 | 1435804 | [0xba2b976d...](https://testnet.etherscan.io/tx/0xba2b976d91a5ec966c8943f20b9543c653019cb1d29c95876e861fb4ee6bc370) |

**Comment by ensrationis** [comment]
@akru please, close issue and use in the future this table: https://github.com/airalab/DAO-factory/blob/master/expenses.md

**Comment by ensrationis** [comment]
https://github.com/airalab/DAO-factory/blob/master/ready-to-work-builders.md
